services:
  app:
    build: .
    container_name: cakephp_app
    volumes:
      - ./app:/var/www/html/app               
      - cakephp_vendor:/var/www/html/app/vendor
    ports:
      - "8080:80"
    depends_on:
      db:
        condition: service_healthy
    environment:      
      SECURITY_SALT: "${SECURITY_SALT}"
      DATABASE_URL: "mysql://${DB_USER}:${DB_PASS}@db:3306/inase_lab"

  db:
    image: mysql:8.0
    container_name: cakephp_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASS}
      MYSQL_DATABASE: inase_lab
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    volumes:
      - ./init-dev.sql:/docker-entrypoint-initdb.d/00-init.sql
      - ./desarrollo.sql:/docker-entrypoint-initdb.d/01-desarrollo.sql    
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1"]
      interval: 5s
      timeout: 3s
      retries: 10

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: cakephp_phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: ${DB_USER}
      PMA_PASSWORD: ${DB_PASS}
    ports:
      - "8081:80"

volumes:
  cakephp_vendor: