services:
  app:
    build: .
    container_name: cakephp_app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=${DB_USER}
      - DATABASE_PASSWORD=${DB_PASS}
      - DATABASE_NAME=inase_lab
    networks:
      - cake_network

  db:
    image: mysql:8.0
    container_name: cakephp_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASS}
      MYSQL_DATABASE: inase_lab
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    volumes:
      - ./init-dev.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - cake_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: cakephp_phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: ${DB_USER}
      PMA_PASSWORD: ${DB_PASS}
    ports:
      - "8081:80"
    networks:
      - cake_network

networks:
  cake_network: