name: Ejecutar tests del proyecto

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: intl, mbstring, pdo_mysql
          tools: composer:v2

      - name: Install Composer Dependencies
        run: |
          cd app
          composer install --no-interaction --no-progress

      - name: Create .env file (if needed)
        run: cp app/config/.env.example app/config/.env

      - name: Run CakePHP Tests
        run: |
          cd app
          chmod +x bin/cake vendor/bin/phpunit
          ./bin/cake migrations migrate --connection test
          vendor/bin/phpunit
